/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3dModels/Traidar_laptop.glb --typescript --precision 3 
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export function TraidarLaptop(props) {
  const group = React.useRef();
  const lidRef = React.useRef();
  const [initRot, setInitRot] = useState(1.931); // Initial rotation.x from the model

  const { nodes, materials } = useGLTF("/3dModels/TraidarLaptop.glb");

  // Animate lid opening and laptop rotation over 2 seconds on load
  useFrame(({ clock }) => {
    if (!lidRef.current || !group.current) return;
    const t = clock.getElapsedTime();
    const progress = Math.min(t / 7, 1);

    // Lid animation
    const startAngle = 1.931; // Closed position
    const endAngle = 0.5; // Open position (approximately 80 degrees)
    lidRef.current.rotation.x = THREE.MathUtils.lerp(
      startAngle,
      endAngle,
      progress
    );

    // Laptop rotation animation
    const rotations = Math.PI * 2; // Full 360 degrees
    group.current.rotation.y = progress * rotations;
  });

  return (
    <group
      ref={group}
      {...props}
      position={[3.5, -3, -5]}
      rotation={[0, 0, 0]}
      scale={30}
      dispose={null}
    >
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="e91829aaa22747909a0071cc2eedf941fbx"
            rotation={[Math.PI / 2, -0.5, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  ref={lidRef}
                  name="pCylinder1"
                  position={[0, 0.046, -12.397]}
                  rotation={[1.931, 0, Math.PI / 2]}
                  scale={[1.146, 1, 1.146]}
                >
                  <group
                    name="pCube3"
                    position={[0.093, 0, -0.466]}
                    rotation={[0, 1.332, -Math.PI / 2]}
                    scale={[1, 0.873, 0.873]}
                  >
                    <group
                      name="pCube2"
                      position={[0, 7.378, 9.958]}
                      rotation={[2.543, 0, 0]}
                      scale={[1, 1.15, 1]}
                    >
                      <group
                        name="pDisc7"
                        position={[0, 0.332, -11.292]}
                        rotation={[0.093, 0, 0]}
                        scale={[0.225, 0.27, 0.225]}
                      >
                        <mesh
                          name="pDisc7_camera_0"
                          geometry={nodes.pDisc7_camera_0.geometry}
                          material={materials.camera}
                        />
                      </group>
                      <group name="polySurface1">
                        <mesh
                          name="polySurface1_Default_Material_0"
                          geometry={
                            nodes.polySurface1_Default_Material_0.geometry
                          }
                          material={materials.Default_Material}
                        />
                        <mesh
                          name="polySurface1_laptopBlack_0"
                          geometry={nodes.polySurface1_laptopBlack_0.geometry}
                          material={materials.laptopBlack}
                        >
                          <mesh
                            name="Mesh_0002"
                            geometry={nodes.Mesh_0002.geometry}
                            material={materials["Material_0.002"]}
                            position={[-0.053, -0.368, 0.22]}
                            rotation={[-1.568, -0.006, -1.013]}
                            scale={[0.115, 0.115, 0.1]}
                          />
                        </mesh>
                        <mesh
                          name="polySurface1_screen_0"
                          geometry={nodes.polySurface1_screen_0.geometry}
                          material={materials.Dash}
                          position={[0, -0.153, -0.069]}
                        />
                      </group>
                      <group name="polySurface2" position={[0, 0.005, 0]} />
                      <group name="polySurface3" position={[0, 0.005, 0]}>
                        <mesh
                          name="polySurface3_glassCracks_0"
                          geometry={nodes.polySurface3_glassCracks_0.geometry}
                          material={materials.glassCracks}
                        />
                      </group>
                      <group name="transform3" />
                    </group>
                    <mesh
                      name="pCube3_laptopBlack_0"
                      geometry={nodes.pCube3_laptopBlack_0.geometry}
                      material={materials.laptopBlack}
                    />
                  </group>
                  <mesh
                    name="pCylinder1_laptopBlack_0"
                    geometry={nodes.pCylinder1_laptopBlack_0.geometry}
                    material={materials.laptopBlack}
                  />
                </group>
                <group
                  name="capsL"
                  position={[-12.742, 0.425, -2.909]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="capsL_keyBlack_0"
                    geometry={nodes.capsL_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="capsL1"
                  position={[9.227, 0.425, -2.909]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="capsL1_keyBlack_0"
                    geometry={nodes.capsL1_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="control"
                  position={[-12.776, 0.425, 1.102]}
                  scale={[1.506, 0.284, 1.603]}
                >
                  <mesh
                    name="control_keyBlack_0"
                    geometry={nodes.control_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="control1"
                  position={[4.893, 0.425, 1.102]}
                  scale={[1.506, 0.284, 1.603]}
                >
                  <mesh
                    name="control1_keyBlack_0"
                    geometry={nodes.control1_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey"
                  position={[-12.708, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey_keyBlack_0"
                    geometry={nodes.defaultKey_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey1"
                  position={[-11.047, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey1_keyBlack_0"
                    geometry={nodes.defaultKey1_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey10"
                  position={[2.398, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey10_keyBlack_0"
                    geometry={nodes.defaultKey10_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey11"
                  position={[0.737, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey11_keyBlack_0"
                    geometry={nodes.defaultKey11_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey12"
                  position={[7.479, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey12_keyBlack_0"
                    geometry={nodes.defaultKey12_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey13"
                  position={[-10.191, 0.425, -4.844]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey13_keyBlack_0"
                    geometry={nodes.defaultKey13_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey14"
                  position={[-8.53, 0.425, -4.844]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey14_keyBlack_0"
                    geometry={nodes.defaultKey14_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey15"
                  position={[-5.15, 0.425, -4.844]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey15_keyBlack_0"
                    geometry={nodes.defaultKey15_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey16"
                  position={[-6.811, 0.425, -4.844]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey16_keyBlack_0"
                    geometry={nodes.defaultKey16_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey17"
                  position={[-0.088, 0.425, -4.844]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey17_keyBlack_0"
                    geometry={nodes.defaultKey17_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey18"
                  position={[1.593, 0.425, -4.844]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey18_keyBlack_0"
                    geometry={nodes.defaultKey18_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey19"
                  position={[-1.787, 0.425, -4.844]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey19_keyBlack_0"
                    geometry={nodes.defaultKey19_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey2"
                  position={[-7.667, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey2_keyBlack_0"
                    geometry={nodes.defaultKey2_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey20"
                  position={[-3.448, 0.425, -4.844]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey20_keyBlack_0"
                    geometry={nodes.defaultKey20_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey21"
                  position={[6.634, 0.425, -4.844]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey21_keyBlack_0"
                    geometry={nodes.defaultKey21_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey22"
                  position={[8.313, 0.425, -4.844]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey22_keyBlack_0"
                    geometry={nodes.defaultKey22_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey23"
                  position={[4.915, 0.425, -4.844]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey23_keyBlack_0"
                    geometry={nodes.defaultKey23_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey24"
                  position={[3.254, 0.425, -4.844]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey24_keyBlack_0"
                    geometry={nodes.defaultKey24_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey27"
                  position={[12.725, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey27_keyBlack_0"
                    geometry={nodes.defaultKey27_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey28"
                  position={[10.91, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey28_keyBlack_0"
                    geometry={nodes.defaultKey28_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey29"
                  position={[12.725, 0.425, -4.831]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey29_keyBlack_0"
                    geometry={nodes.defaultKey29_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey3"
                  position={[-9.328, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey3_keyBlack_0"
                    geometry={nodes.defaultKey3_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey32"
                  position={[-7.667, 0.425, -2.903]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey32_keyBlack_0"
                    geometry={nodes.defaultKey32_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey33"
                  position={[-9.328, 0.425, -2.903]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey33_keyBlack_0"
                    geometry={nodes.defaultKey33_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey34"
                  position={[-2.585, 0.425, -2.903]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey34_keyBlack_0"
                    geometry={nodes.defaultKey34_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey35"
                  position={[-0.924, 0.425, -2.903]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey35_keyBlack_0"
                    geometry={nodes.defaultKey35_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey36"
                  position={[-4.304, 0.425, -2.903]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey36_keyBlack_0"
                    geometry={nodes.defaultKey36_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey37"
                  position={[-5.965, 0.425, -2.903]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey37_keyBlack_0"
                    geometry={nodes.defaultKey37_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey38"
                  position={[4.117, 0.425, -2.903]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey38_keyBlack_0"
                    geometry={nodes.defaultKey38_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey39"
                  position={[5.778, 0.425, -2.903]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey39_keyBlack_0"
                    geometry={nodes.defaultKey39_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey4"
                  position={[-2.585, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey4_keyBlack_0"
                    geometry={nodes.defaultKey4_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey40"
                  position={[2.398, 0.425, -2.903]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey40_keyBlack_0"
                    geometry={nodes.defaultKey40_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey41"
                  position={[0.737, 0.425, -2.903]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey41_keyBlack_0"
                    geometry={nodes.defaultKey41_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey42"
                  position={[7.479, 0.425, -2.903]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey42_keyBlack_0"
                    geometry={nodes.defaultKey42_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey44"
                  position={[-8.53, 0.425, -0.876]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey44_keyBlack_0"
                    geometry={nodes.defaultKey44_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey45"
                  position={[-5.15, 0.425, -0.876]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey45_keyBlack_0"
                    geometry={nodes.defaultKey45_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey46"
                  position={[-6.811, 0.425, -0.876]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey46_keyBlack_0"
                    geometry={nodes.defaultKey46_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey47"
                  position={[-0.068, 0.425, -0.876]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey47_keyBlack_0"
                    geometry={nodes.defaultKey47_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey48"
                  position={[1.593, 0.425, -0.876]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey48_keyBlack_0"
                    geometry={nodes.defaultKey48_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey49"
                  position={[-1.787, 0.425, -0.876]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey49_keyBlack_0"
                    geometry={nodes.defaultKey49_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey5"
                  position={[-0.924, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey5_keyBlack_0"
                    geometry={nodes.defaultKey5_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey50"
                  position={[-3.448, 0.425, -0.876]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey50_keyBlack_0"
                    geometry={nodes.defaultKey50_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey51"
                  position={[6.65, 0.425, -0.876]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey51_keyBlack_0"
                    geometry={nodes.defaultKey51_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey53"
                  position={[4.945, 0.425, -0.876]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey53_keyBlack_0"
                    geometry={nodes.defaultKey53_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey54"
                  position={[3.254, 0.425, -0.876]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey54_keyBlack_0"
                    geometry={nodes.defaultKey54_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey55"
                  position={[12.725, 0.425, -2.903]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey55_keyBlack_0"
                    geometry={nodes.defaultKey55_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey56"
                  position={[12.7, 0.425, -0.876]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey56_keyBlack_0"
                    geometry={nodes.defaultKey56_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey57"
                  position={[-10.31, 0.425, 1.102]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey57_keyBlack_0"
                    geometry={nodes.defaultKey57_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey58"
                  position={[-8.519, 0.425, 1.102]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey58_keyBlack_0"
                    geometry={nodes.defaultKey58_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey59"
                  position={[-6.787, 0.425, 1.102]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey59_keyBlack_0"
                    geometry={nodes.defaultKey59_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey6"
                  position={[-4.304, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey6_keyBlack_0"
                    geometry={nodes.defaultKey6_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey60"
                  position={[3.26, 0.425, 1.102]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey60_keyBlack_0"
                    geometry={nodes.defaultKey60_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey61"
                  position={[12.702, 0.425, 1.102]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey61_keyBlack_0"
                    geometry={nodes.defaultKey61_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey7"
                  position={[-5.965, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey7_keyBlack_0"
                    geometry={nodes.defaultKey7_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey8"
                  position={[4.117, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey8_keyBlack_0"
                    geometry={nodes.defaultKey8_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="defaultKey9"
                  position={[5.778, 0.425, -6.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="defaultKey9_keyBlack_0"
                    geometry={nodes.defaultKey9_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey"
                  position={[-12.802, 0.425, -7.993]}
                  scale={[1.412, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey_keyBlack_0"
                    geometry={nodes.escapeKey_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey1"
                  position={[-11.257, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey1_keyBlack_0"
                    geometry={nodes.escapeKey1_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey10"
                  position={[5.216, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey10_keyBlack_0"
                    geometry={nodes.escapeKey10_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey11"
                  position={[3.697, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey11_keyBlack_0"
                    geometry={nodes.escapeKey11_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey12"
                  position={[2.176, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey12_keyBlack_0"
                    geometry={nodes.escapeKey12_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey13"
                  position={[9.851, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey13_keyBlack_0"
                    geometry={nodes.escapeKey13_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey14"
                  position={[8.308, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey14_keyBlack_0"
                    geometry={nodes.escapeKey14_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey15"
                  position={[6.727, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey15_keyBlack_0"
                    geometry={nodes.escapeKey15_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey16"
                  position={[12.869, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey16_keyBlack_0"
                    geometry={nodes.escapeKey16_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey17"
                  position={[11.327, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey17_keyBlack_0"
                    geometry={nodes.escapeKey17_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey18"
                  position={[9.108, 0.425, 1.75]}
                  scale={[1.547, 0.284, 1.398]}
                >
                  <mesh
                    name="escapeKey18_keyBlack_0"
                    geometry={nodes.escapeKey18_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey19"
                  position={[7.433, 0.425, 1.75]}
                  scale={[1.547, 0.284, 1.398]}
                >
                  <mesh
                    name="escapeKey19_keyBlack_0"
                    geometry={nodes.escapeKey19_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey2"
                  position={[-9.773, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey2_keyBlack_0"
                    geometry={nodes.escapeKey2_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey20"
                  position={[10.796, 0.425, 1.75]}
                  scale={[1.547, 0.284, 1.398]}
                >
                  <mesh
                    name="escapeKey20_keyBlack_0"
                    geometry={nodes.escapeKey20_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey21"
                  position={[9.108, 0.425, 0.752]}
                  scale={[1.547, 0.284, 1.398]}
                >
                  <mesh
                    name="escapeKey21_keyBlack_0"
                    geometry={nodes.escapeKey21_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey3"
                  position={[-8.287, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey3_keyBlack_0"
                    geometry={nodes.escapeKey3_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey4"
                  position={[-3.866, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey4_keyBlack_0"
                    geometry={nodes.escapeKey4_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey5"
                  position={[-5.337, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey5_keyBlack_0"
                    geometry={nodes.escapeKey5_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey6"
                  position={[-6.805, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey6_keyBlack_0"
                    geometry={nodes.escapeKey6_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey7"
                  position={[0.645, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey7_keyBlack_0"
                    geometry={nodes.escapeKey7_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey8"
                  position={[-0.857, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey8_keyBlack_0"
                    geometry={nodes.escapeKey8_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="escapeKey9"
                  position={[-2.376, 0.425, -7.993]}
                  scale={[1.349, 0.284, 1.603]}
                >
                  <mesh
                    name="escapeKey9_keyBlack_0"
                    geometry={nodes.escapeKey9_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group name="pCube1">
                  <mesh
                    name="pCube1_Default_Material_0"
                    geometry={nodes.pCube1_Default_Material_0.geometry}
                    material={materials.Default_Material}
                  />
                  <mesh
                    name="pCube1_lambert1_0"
                    geometry={nodes.pCube1_lambert1_0.geometry}
                    material={materials.lambert1}
                  />
                  <mesh
                    name="pCube1_laptopBlack_0"
                    geometry={nodes.pCube1_laptopBlack_0.geometry}
                    material={materials.laptopBlack}
                  />
                  <mesh
                    name="pCube1_typeBlinn1_0"
                    geometry={nodes.pCube1_typeBlinn1_0.geometry}
                    material={materials.typeBlinn1}
                  />
                </group>
                <group
                  name="pDisc3"
                  position={[15, -0.719, -9]}
                  rotation={[Math.PI, 0, 0]}
                >
                  <mesh
                    name="pDisc3_bumpers_0"
                    geometry={nodes.pDisc3_bumpers_0.geometry}
                    material={materials.bumpers}
                  />
                </group>
                <group
                  name="pDisc4"
                  position={[15, -0.719, 9]}
                  rotation={[Math.PI, 0, 0]}
                >
                  <mesh
                    name="pDisc4_bumpers_0"
                    geometry={nodes.pDisc4_bumpers_0.geometry}
                    material={materials.bumpers}
                  />
                </group>
                <group
                  name="pDisc5"
                  position={[-15, -0.719, 9]}
                  rotation={[Math.PI, 0, 0]}
                >
                  <mesh
                    name="pDisc5_bumpers_0"
                    geometry={nodes.pDisc5_bumpers_0.geometry}
                    material={materials.bumpers}
                  />
                </group>
                <group
                  name="pDisc6"
                  position={[-15, -0.719, -9]}
                  rotation={[Math.PI, 0, 0]}
                >
                  <mesh
                    name="pDisc6_bumpers_0"
                    geometry={nodes.pDisc6_bumpers_0.geometry}
                    material={materials.bumpers}
                  />
                </group>
                <group
                  name="pPlane1"
                  position={[-13.317, 0.605, 9.175]}
                  rotation={[0, -0.917, 0]}
                />
                <group
                  name="shift"
                  position={[-12.742, 0.425, -0.87]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="shift_keyBlack_0"
                    geometry={nodes.shift_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="shift1"
                  position={[8.381, 0.425, -0.87]}
                  scale={[1.629, 0.284, 1.603]}
                >
                  <mesh
                    name="shift1_keyBlack_0"
                    geometry={nodes.shift1_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="shift2"
                  position={[-5.095, 0.425, 1.102]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="shift2_keyBlack_0"
                    geometry={nodes.shift2_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="tabKey"
                  position={[-12.742, 0.425, -4.844]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="tabKey_keyBlack_0"
                    geometry={nodes.tabKey_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="tabKey1"
                  position={[10.027, 0.425, -4.844]}
                  scale={[1.603, 0.284, 1.603]}
                >
                  <mesh
                    name="tabKey1_keyBlack_0"
                    geometry={nodes.tabKey1_keyBlack_0.geometry}
                    material={materials.keyBlack}
                  />
                </group>
                <group
                  name="typeMesh1"
                  position={[-13.124, 0.572, -8.215]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh1_keyText_0"
                    geometry={nodes.typeMesh1_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh10"
                  position={[-3.985, 0.572, -8.215]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh10_keyText_0"
                    geometry={nodes.typeMesh10_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh11"
                  position={[-2.45, 0.572, -8.215]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh11_keyText_0"
                    geometry={nodes.typeMesh11_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh12"
                  position={[-0.83, 0.572, -8.215]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh12_keyText_0"
                    geometry={nodes.typeMesh12_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh13"
                  position={[0.601, 0.572, -8.215]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh13_keyText_0"
                    geometry={nodes.typeMesh13_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh14"
                  position={[2.187, 0.572, -8.215]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh14_keyText_0"
                    geometry={nodes.typeMesh14_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh15"
                  position={[3.663, 0.572, -8.215]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh15_keyText_0"
                    geometry={nodes.typeMesh15_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh16"
                  position={[5.182, 0.572, -8.215]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh16_keyText_0"
                    geometry={nodes.typeMesh16_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh17"
                  position={[6.68, 0.572, -8.394]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh17_keyText_0"
                    geometry={nodes.typeMesh17_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh18"
                  position={[8.286, 0.572, -8.271]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh18_keyText_0"
                    geometry={nodes.typeMesh18_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh19"
                  position={[9.846, 0.572, -8.271]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh19_keyText_0"
                    geometry={nodes.typeMesh19_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh2"
                  position={[-13.028, 0.572, -4.68]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh2_keyText_0"
                    geometry={nodes.typeMesh2_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh20"
                  position={[11.309, 0.572, -8.271]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh20_keyText_0"
                    geometry={nodes.typeMesh20_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh21"
                  position={[12.84, 0.572, -8.271]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh21_keyText_0"
                    geometry={nodes.typeMesh21_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh22"
                  position={[-11.061, 0.572, -6.696]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh22_keyText_0"
                    geometry={nodes.typeMesh22_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh23"
                  position={[-9.364, 0.572, -6.696]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh23_keyText_0"
                    geometry={nodes.typeMesh23_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh24"
                  position={[-7.697, 0.572, -6.696]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh24_keyText_0"
                    geometry={nodes.typeMesh24_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh25"
                  position={[-6.041, 0.572, -6.696]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh25_keyText_0"
                    geometry={nodes.typeMesh25_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh26"
                  position={[-4.339, 0.572, -6.696]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh26_keyText_0"
                    geometry={nodes.typeMesh26_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh27"
                  position={[-2.625, 0.572, -6.696]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh27_keyText_0"
                    geometry={nodes.typeMesh27_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh28"
                  position={[-0.97, 0.572, -6.696]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh28_keyText_0"
                    geometry={nodes.typeMesh28_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh29"
                  position={[0.698, 0.572, -6.696]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh29_keyText_0"
                    geometry={nodes.typeMesh29_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh3"
                  position={[-13.032, 0.572, -2.764]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh3_keyText_0"
                    geometry={nodes.typeMesh3_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh30"
                  position={[2.377, 0.572, -6.696]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh30_keyText_0"
                    geometry={nodes.typeMesh30_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh31"
                  position={[4.079, 0.572, -6.696]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh31_keyText_0"
                    geometry={nodes.typeMesh31_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh32"
                  position={[5.746, 0.572, -6.696]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh32_keyText_0"
                    geometry={nodes.typeMesh32_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh33"
                  position={[7.507, 0.572, -6.696]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh33_keyText_0"
                    geometry={nodes.typeMesh33_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh34"
                  position={[10.066, 0.572, -6.73]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh34_keyText_0"
                    geometry={nodes.typeMesh34_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh35"
                  position={[12.715, 0.572, -6.73]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh35_keyText_0"
                    geometry={nodes.typeMesh35_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh36"
                  position={[12.715, 0.572, -4.754]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh36_keyText_0"
                    geometry={nodes.typeMesh36_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh37"
                  position={[12.715, 0.572, -2.798]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh37_keyText_0"
                    geometry={nodes.typeMesh37_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh38"
                  position={[12.715, 0.572, -0.759]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh38_keyText_0"
                    geometry={nodes.typeMesh38_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh39"
                  position={[12.715, 0.572, 1.156]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh39_keyText_0"
                    geometry={nodes.typeMesh39_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh4"
                  position={[-13.112, 0.572, -6]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh4_keyText_0"
                    geometry={nodes.typeMesh4_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh40"
                  position={[10.811, 0.572, -2.798]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh40_keyText_0"
                    geometry={nodes.typeMesh40_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh41"
                  position={[10.811, 0.572, -0.733]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh41_keyText_0"
                    geometry={nodes.typeMesh41_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh42"
                  position={[5.328, 0.572, 1.283]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh42_keyText_0"
                    geometry={nodes.typeMesh42_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh43"
                  position={[3.298, 0.572, 1.283]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh43_keyText_0"
                    geometry={nodes.typeMesh43_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh44"
                  position={[-6.804, 0.572, 1.283]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh44_keyText_0"
                    geometry={nodes.typeMesh44_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh45"
                  position={[-12.259, 0.572, 1.283]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh45_keyText_0"
                    geometry={nodes.typeMesh45_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh46"
                  position={[-12.538, 0.572, -0.733]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh46_keyText_0"
                    geometry={nodes.typeMesh46_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh47"
                  position={[-10.329, 0.572, 1.156]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh47_keyText_0"
                    geometry={nodes.typeMesh47_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh48"
                  position={[7.402, 0.572, 1.597]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh48_keyText_0"
                    geometry={nodes.typeMesh48_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh49"
                  position={[9.272, 0.572, 1.522]}
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                >
                  <mesh
                    name="typeMesh49_keyText_0"
                    geometry={nodes.typeMesh49_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh5"
                  position={[-11.331, 0.572, -8.215]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh5_keyText_0"
                    geometry={nodes.typeMesh5_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh50"
                  position={[9.017, 0.572, 0.44]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                >
                  <mesh
                    name="typeMesh50_keyText_0"
                    geometry={nodes.typeMesh50_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh51"
                  position={[10.823, 0.572, 1.348]}
                  rotation={[-Math.PI / 2, 0, Math.PI]}
                >
                  <mesh
                    name="typeMesh51_keyText_0"
                    geometry={nodes.typeMesh51_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh52"
                  position={[-10.245, 0.572, -4.709]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh52_keyText_0"
                    geometry={nodes.typeMesh52_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh53"
                  position={[-8.594, 0.572, -4.709]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh53_keyText_0"
                    geometry={nodes.typeMesh53_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh54"
                  position={[-6.846, 0.572, -4.709]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh54_keyText_0"
                    geometry={nodes.typeMesh54_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh55"
                  position={[-5.291, 0.572, -4.709]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh55_keyText_0"
                    geometry={nodes.typeMesh55_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh56"
                  position={[-3.505, 0.572, -4.709]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh56_keyText_0"
                    geometry={nodes.typeMesh56_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh57"
                  position={[-1.796, 0.572, -4.709]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh57_keyText_0"
                    geometry={nodes.typeMesh57_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh58"
                  position={[-0.145, 0.572, -4.709]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh58_keyText_0"
                    geometry={nodes.typeMesh58_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh59"
                  position={[1.507, 0.572, -4.709]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh59_keyText_0"
                    geometry={nodes.typeMesh59_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh6"
                  position={[-9.818, 0.572, -8.215]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh6_keyText_0"
                    geometry={nodes.typeMesh6_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh60"
                  position={[3.178, 0.572, -4.709]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh60_keyText_0"
                    geometry={nodes.typeMesh60_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh61"
                  position={[4.829, 0.572, -4.709]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh61_keyText_0"
                    geometry={nodes.typeMesh61_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh62"
                  position={[6.596, 0.572, -4.709]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh62_keyText_0"
                    geometry={nodes.typeMesh62_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh63"
                  position={[8.247, 0.572, -4.709]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh63_keyText_0"
                    geometry={nodes.typeMesh63_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh64"
                  position={[10.359, 0.572, -4.709]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh64_keyText_0"
                    geometry={nodes.typeMesh64_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh65"
                  position={[-9.304, 0.572, -2.77]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh65_keyText_0"
                    geometry={nodes.typeMesh65_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh66"
                  position={[-7.749, 0.572, -2.77]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh66_keyText_0"
                    geometry={nodes.typeMesh66_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh67"
                  position={[-6.021, 0.572, -2.77]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh67_keyText_0"
                    geometry={nodes.typeMesh67_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh68"
                  position={[-4.388, 0.572, -2.77]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh68_keyText_0"
                    geometry={nodes.typeMesh68_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh69"
                  position={[-2.641, 0.572, -2.77]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh69_keyText_0"
                    geometry={nodes.typeMesh69_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh7"
                  position={[-8.381, 0.572, -8.215]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh7_keyText_0"
                    geometry={nodes.typeMesh7_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh70"
                  position={[-1.047, 0.572, -2.77]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh70_keyText_0"
                    geometry={nodes.typeMesh70_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh71"
                  position={[0.662, 0.572, -2.77]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh71_keyText_0"
                    geometry={nodes.typeMesh71_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh72"
                  position={[2.429, 0.572, -2.77]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh72_keyText_0"
                    geometry={nodes.typeMesh72_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh73"
                  position={[4.042, 0.572, -2.77]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh73_keyText_0"
                    geometry={nodes.typeMesh73_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh74"
                  position={[5.732, 0.572, -2.77]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh74_keyText_0"
                    geometry={nodes.typeMesh74_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh75"
                  position={[7.345, 0.572, -2.77]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh75_keyText_0"
                    geometry={nodes.typeMesh75_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh76"
                  position={[-8.507, 0.572, -0.703]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh76_keyText_0"
                    geometry={nodes.typeMesh76_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh77"
                  position={[-6.88, 0.572, -0.703]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh77_keyText_0"
                    geometry={nodes.typeMesh77_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh78"
                  position={[-5.188, 0.572, -0.703]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh78_keyText_0"
                    geometry={nodes.typeMesh78_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh79"
                  position={[-3.463, 0.572, -0.703]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh79_keyText_0"
                    geometry={nodes.typeMesh79_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh8"
                  position={[-6.868, 0.572, -8.215]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh8_keyText_0"
                    geometry={nodes.typeMesh8_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh80"
                  position={[-1.787, 0.572, -0.703]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh80_keyText_0"
                    geometry={nodes.typeMesh80_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh81"
                  position={[-0.16, 0.572, -0.703]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh81_keyText_0"
                    geometry={nodes.typeMesh81_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh82"
                  position={[1.532, 0.572, -0.703]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh82_keyText_0"
                    geometry={nodes.typeMesh82_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh83"
                  position={[3.191, 0.572, -0.703]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh83_keyText_0"
                    geometry={nodes.typeMesh83_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh84"
                  position={[4.9, 0.572, -0.703]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh84_keyText_0"
                    geometry={nodes.typeMesh84_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh85"
                  position={[6.559, 0.572, -0.703]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh85_keyText_0"
                    geometry={nodes.typeMesh85_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
                <group
                  name="typeMesh9"
                  position={[-5.39, 0.572, -8.215]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="typeMesh9_keyText_0"
                    geometry={nodes.typeMesh9_keyText_0.geometry}
                    material={materials.keyText}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Node_6" position={[0, 0, -0.02]}>
          <group name="Node_5">
            <group name="Node_4" position={[0.077, 0.042, -0.077]}>
              <group name="Node_3">
                <group
                  name="Node_2"
                  rotation={[Math.PI, -Math.PI / 4, Math.PI]}
                  scale={-2.381}
                >
                  <group name="Node_1" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3dModels/TraidarLaptop.glb");
