/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/3dModels/TraidarLogo.glb --types --transform 
Files: ./public/3dModels/TraidarLogo.glb [1.79MB] > C:\Users\muzik\Documents\traidar-landing\TraidarLogo-transformed.glb [123.11KB] (93%)
*/

import * as THREE from "three";
import React, { type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    model: THREE.Mesh;
  };
  materials: {
    CustomMaterial: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function TraidarLogoModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/3dModels/TraidarLogo-transformed.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null} scale={10}>
      <mesh
        geometry={nodes.model.geometry}
        material={materials.CustomMaterial}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/3dModels/TraidarLogo-transformed.glb");
